# Upadate the List in reverse order...
l1=[34,23,11,12,13,14,15,16,66,36]
# l1.reverse()
# print(l1)
# l1.append("Gaurang")#append : add to the end of written document...
# l1.append(34)# 34 is integer
# l1.append("34")# 34 is string...
# l1.insert(1,34)# It's means insert 34 at index 1...
# l1.insert(34,1)# It' s means insert 1 at index 34...but there is no elements fill up 34 so to avoid memory leakage
# python save 1 at the last index automatically in program...
l1.pop(1)# in pop function we input list index at which we want to remove element in list...
l1.remove(34)# In remove function we input list element which we want to remove for the list...
print(l1)
